version: 2.1

orbs:
  maven: circleci/maven@1.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:16-buster-node
        environment:
          MAVEN_OPTS: -Xmx1024m
    working_directory: ~/mobiquityQACodingAssignment
    steps:
    - checkout:
        path: ~/mobiquityQACodingAssignment
    - run:
        name: Run JsonPlaceholder Tests
        command: mvn clean test
        when: always
    # - run:
    #     name: Generate environment properties
    #     command: echo -e "BUILD_NUM=$CIRCLE_BUILD_NUM \nstaging=${STAGING:-alpha}" >> target/allure-results/allure.properties
    #     when: always
    - run:
        name: Make history dir for allure
        command: mkdir target/allure-results/history
        when: always
    - run:
        name: Get previous artifact links
        command: curl https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PREVIOUS_BUILD_NUM/artifacts?circle-token=$artifacts | grep -o 'https:\/\/[^"]*Allure\/history\/.*\.json' > artifacts.txt || true
        when: always
    # - run: cat artifacts.txt
    - run:
        name: Download history artifacts
        command: <artifacts.txt xargs -P4 -I % wget %?circle-token=$artifacts
        when: always
    - run:
        name: Rename and copy history artifacts to allure-result
        command: |
          mv history.json?circle-token=$artifacts history.json && mv history-trend.json?circle-token=$artifacts history-trend.json || true
          cp history.json target/allure-results/history/ && cp history-trend.json target/allure-results/history/ || true
          mv categories-trend.json?circle-token=$artifacts categories-trend.json && mv duration-trend.json?circle-token=$artifacts duration-trend.json || true
          cp categories-trend.json target/allure-results/history/ && cp duration-trend.json target/allure-results/history/ || true
          mv retry-trend.json?circle-token=$artifacts retry-trend.json || true
          cp retry-trend.json target/allure-results/history/ || true
        when: always

    - run:
        name: Allure Report
        command: mvn allure:report
        when: always

    - save_cache:
        paths:
          - ~/.m2
          - allure-results
          - target
        key: $CIRCLE_PROJECT_REPONAME-{{ checksum "pom.xml" }}
        when: always
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: target/allure-results
        #destination: report/allure-results
    - store_artifacts:
        path: target/site/allure-maven-plugin
        destination: Allure

workflows:
  version: 2
  autotests_and_report:
    jobs:
      - build